version: '3.8'
services:
  express:
    image: giftr_db
    container_name: giftr_db
    environment:
      GIFTR_JWTKEY: superSecretKey
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js