version: '3.8'
services:
  express:
    image: giftr_api
    container_name: giftr_api
    environment:
      API_JWTKEY: oilyg1440kywh5jiccv17wlp0ddrwl
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js